global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'gybraty@gmail.com'
  smtp_auth_username: 'gybraty@gmail.com'
  smtp_auth_password: 'qphe yjuz pcud xcvn'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-receiver'

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'kakuzofa@gmail.com'
    send_resolved: true
