global:
  scrape_interval:     15s
  evaluation_interval: 15s  # How frequently to evaluate alerts

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
          
scrape_configs:
  - job_name: 'shuup'
    static_configs:
      - targets: ['shuup:8000']



rule_files:
  - "alert_rules.yml"  # Define alert rules in this file
