version: "3.7"

services:
  shuup:
    build:
      context: .
    ports:
      - "8000:8000"
    tty: true
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"  # Adjust ports as needed
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus configuration

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Adjust ports as needed