global:
  scrape_interval:     15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
          
scrape_configs:
  - job_name: 'shuup'
    static_configs:
      - targets: ['shuup:8000']

      